baseURL = 'https://liangcc.me/'
languageCode = 'en-us'
title = "CC's blog"
theme = 'chalk'

[params.chalk]
  # chalk theme parameters
  about_enabled = true # Change to true if you wish to show an icon in the navigation that redirects to the about page
  scrollappear_enabled = true
  theme_toggle = true
  rss_enabled = true
  local_fonts = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"

[params]
  description = 'Random thoughts'
  images = ['images/buffaloes.png']
  title = "CC's blog"
